version: "3.7"
services:
  fast_app:
    build: './fast_app'
    depends_on:
      - redis
      - worker

  worker:
    build: './worker'
    user: nobody
    depends_on:
      - redis

  redis:
    image: 'redis:5'
    ports:
      - '6379:6379'